### ISSUE TITLE
0.1.0 -- Install error

### ISSUE THREAD

**Issue by klen** [getsentry/raven-aiohttp#2]
Looks like you are forgot about MANIFEST.in

```
$ pip install raven-aiohttp
Collecting raven-aiohttp
  Using cached raven-aiohttp-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/00/2hr1h5ks56l0r__5dh6xkcv00000gp/T/pip-build-ys5lietj/raven-aiohttp/setup.py", line 50, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by mattrobenolt** [comment]
gj @dcramer. Fix coming soon. :) Sorry about that.

**Comment by mattrobenolt** [comment]
@klen Pushed 0.1.1 which should fix this.

**Comment by klen** [comment]
Thank you!
